import 'weather-icons/css/weather-icons.css'

const weather_night_icons = {
    "200": "wi-night-thunderstorm",
    "201": "wi-night-storm-showers",
    "202": "wi-night-thunderstorm",
    "210": "wi-night-thunderstorm",
    "211": "wi-night-thunderstorm",
    "212": "wi-night-thunderstorm",
    "221": "wi-night-thunderstorm",
    "230": "wi-night-thunderstorm",
    "231": "wi-night-thunderstorm",
    "232": "wi-night-thunderstorm",

    "300": "wi-night-alt-sprinkle",
    "301": "wi-night-alt-sprinkle",
    "302": "wi-night-showers",
    "310": "wi-night-showers",
    "311": "wi-night-showers",
    "312": "wi-night-showers",
    "313": "wi-night-showers",
    "314": "wi-night-showers",
    "321": "wi-night-showers",

    "500": "wi-night-showers",
    "501": "wi-night-showers",
    "502": "wi-night-alt-rain",
    "503": "wi-night-alt-rain",
    "504": "wi-night-alt-rain",
    "511": "wi-night-hail",
    "520": "wi-night-alt-rain",
    "521": "wi-night-alt-rain",
    "522": "wi-night-alt-rain",
    "531": "wi-night-alt-rain",

    "600": "wi-night-snow",
    "601": "wi-night-snow",
    "602": "wi-night-snow",
    "611": "wi-night-alt-sleet",
    "612": "wi-night-alt-sleet",
    "613": "wi-night-alt-sleet",
    "615": "wi-night-rain-mix",
    "616": "wi-night-rain-mix",
    "620": "wi-night-alt-rain-mix",
    "621": "wi-night-alt-rain-mix",
    "622": "wi-night-alt-rain-mix",

    "701": "wi-night-fog",
    "711": "wi-night-fog",
    "721": "wi-fog",
    "731": "wi-sandstorm",
    "741": "wi-night-fog",
    "751": "wi-sandstorm",
    "761": "wi-sandstorm",
    "762": "wi-sandstorm",
    "771": "wi-sandstorm",
    "781": "wi-tornado",

    "800": "wi-night-clear",
    "801": "wi-night-alt-cloudy",
    "802": "wi-cloud",
    "803": "wi-cloudy",
    "804": "wi-cloudy",
}

export default weather_night_icons